notify = true 
use_nerdfont = true
default_keymappings = false

[notification_format]
title = "%title"
body = "%artists"

[keybindings]
"Enter" = "play"
"Shift+r" = "reconnect"
"Shift+q" = "quit"
"Ctrl+p" = "playpause"
"Ctrl+s" = "focus search"
"Ctrl+a" = "focus queue"
"Ctrl+d" = "focus library"
"Ctrl+i" = "playnext"
"+" = "volup 1"
"-" = "voldown 1"
"i" = "play"
"q" = "back"
"s" = "save"
"o" = "open selected"
"Shift+o" = "open current"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"Left" = "move left 1"
"Down" = "move down 1"
"Up" = "move up 1"
"Right" = "move right 1"
"<" = "previous"
">" = "next"
"?" = "help"
