// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupExperimentPrefs.network.http.http3.retry_different_ip_family", false);
user_pref("app.normandy.user_id", "17f518db-ccc2-4dbd-b41f-5421d0f6a5df");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1694455108);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1694455105);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{b641dc98-7499-4a42-add3-4df331c0b24e}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1694455103);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 139);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ade1f829-a599-4e53-8061-16d10d71d58f}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1694455105);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1694455108528");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1694476708528");
user_pref("browser.search.region", "GB");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1694455105");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230828231221");
user_pref("browser.startup.homepage_override.mstone", "117.0");
user_pref("browser.startup.lastColdStartupCheck", 1694455104);
user_pref("browser.topsites.contile.cacheValidFor", 11921);
user_pref("browser.topsites.contile.cachedTiles", "[{\"id\":74357,\"name\":\"Amazon\",\"url\":\"https://www.amazon.co.uk/?tag=admpdesktopuk-21&ref=pd_sl_02be79bc42fb957eedca0af5219d043d319cd608ca95d62748c6d82b&mfadid=adm\",\"click_url\":\"https://bridge.sfo1.ap01.net/ctp?version=16.0.0&key=1694449268400900002.1&ci=1694449268858.12791&ctag=pd_sl_02be79bc42fb957eedca0af5219d043d319cd608ca95d62748c6d82b\",\"image_url\":\"https://contile-images.services.mozilla.com/obgoOYObjIFea_bXuT6L4LbBJ8j425AD87S1HMD3BWg.9991.jpg\",\"image_size\":200,\"impression_url\":\"https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4Qqk4p2%2BfQHa4pbW1CbWfpbY7ReNxR3UIG8zInwYIFIVs9eYiGINHrwkiFXwxYIZjF8XgClWfC2X7R4dHQ8zJnErj%3DcO7R4dHQfz4Z2Z4CxnHG3Z5FwqgCfX1p8d4Cxr1BINI9HuiF2z4Z2Z4CxnHmcux%3DcvImauiF2zfQlXfplX7ncqIr7VjGbuiF2zfCfdfC2X4Qfnj9wWIBdvIpkY7R4TJr2uJREuHnEYgClnHr7wHG3vjnDuiF2z4Zfd7ReTHF4wJFEUjtdvIpkXfpbr\"},{\"id\":74577,\"name\":\"Vodafone\",\"url\":\"https://www.vodafone.co.uk/?cid=ppc-UK_21_AO_P_X_J_I_D_CBU-PAYM_BAU_Promo_Text-Generic_admarketplace-Privacy_NA_NA_NA_NA_Mix_Mix_NA-AMP&kpid=admp_cmp-219173_kwd-351169009&vfadid=219173&gclid=e1694449268400900002&mfadid=adm\",\"click_url\":\"https://bridge.sfo1.admarketplace.net/ctp?version=16.0.0&key=1694449268400900002.2&ci=1694449268858.12791&ctag=1694449268400900002\",\"image_url\":\"https://contile-images.services.mozilla.com/ff_gz8_WY_1zSHnxaFrWRx3pNVwYIRFzPeioiGEjSyc.18637.jpg\",\"image_size\":200,\"impression_url\":\"https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4Qqk4p2%2BfQHa4pbW1CbWfpbY7ReNxR3UIG8zInwYIFIVs9eYiGINHrwkiFXwxYIZjF8XgClWfC2X7R4dHQ8zJnErj%3DcO7R4dHQfz4Z2d4ZxnHG3Z5FwqgCfX1p8d4Cxr1BINI9HuiF2z4Z2d4ZxnHmcux%3DcvImauiF2zfQl%2BfCxZ7ncqIr7VjGbuiF2zfCDY4Cba4Zqnj9wWIBdvIpkY7R4TJr2uJREuHnEYgC8nHr7wHG3vjnDuiF2zfCD%2BfBIWJ%3DcQIFdwJR2uiF2zfCbW4Wyy\"}]");
user_pref("browser.topsites.contile.lastFetch", 1694455105);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1694455104985");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "117.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "GB");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "96abd014cdf54bf68749e479e91715a7");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230828231221");
user_pref("extensions.lastAppVersion", "117.0");
user_pref("extensions.lastPlatformVersion", "117.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"1ff578d0-42c0-4569-83b9-9571aa207424\",\"pictureinpicture@mozilla.org\":\"fd6672cb-4d29-41a6-8900-499b225ea6f2\",\"screenshots@mozilla.org\":\"88665e2c-2aea-4465-b145-24b650b64f01\",\"webcompat-reporter@mozilla.org\":\"d75dc2f7-6f52-4052-8604-d539c2621f90\",\"webcompat@mozilla.org\":\"5c950831-3ad4-454f-a004-d86d35594beb\",\"default-theme@mozilla.org\":\"855d6d0f-c9df-4da0-8cc8-1e2a9cc92722\",\"addons-search-detection@mozilla.com\":\"ca1ffe9a-05cf-495b-9ce9-6970a1ff01fc\",\"google@search.mozilla.org\":\"651ebc24-f15b-43d8-9933-25e4e6a0a9e8\",\"wikipedia@search.mozilla.org\":\"24cf052f-2390-4ae7-ba86-47de101ae13c\",\"bing@search.mozilla.org\":\"b1cc2fe9-2ba7-4fb1-a16b-8501b70a5d3e\",\"ddg@search.mozilla.org\":\"84f350bb-f5cb-4231-bf12-178776fa1dc9\",\"amazon@search.mozilla.org\":\"f306536c-d13d-4430-85e1-d6b39b830645\",\"ebay@search.mozilla.org\":\"f98b95ad-a0fb-4881-9ca9-5bb7241407d6\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdatastore.frecency", "{\"slug\":\"origins-ranking-experiment\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"frecency\"},\"features\":null},\"active\":true,\"enrollmentId\":\"9449b565-217a-47aa-93d6-8b97291cbe5d\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"Origins Ranking Experiment\",\"userFacingDescription\":\"This experiment aims to validate an improved ranking algorithm for address bar autofill.\",\"lastSeen\":\"2023-09-11T17:58:25.181Z\",\"featureIds\":[\"frecency\"],\"prefs\":[{\"name\":\"places.frecency.origins.alternative.featureGate\",\"branch\":\"user\",\"featureId\":\"frecency\",\"variable\":\"originsAlternativeEnable\",\"originalValue\":null}],\"isRollout\":false}");
user_pref("nimbus.syncdatastore.frecency.originsAlternativeEnable", false);
user_pref("nimbus.syncdatastore.fullPageTranslation", "{\"slug\":\"fullpage-translations\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"fullPageTranslation\"},\"features\":null},\"active\":true,\"enrollmentId\":\"8052d7ed-710a-4f9f-8e46-802551ba5058\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"Fullpage Translations\",\"userFacingDescription\":\"Fullpage Translations is the first native Translations feature we are planning to launch for Firefox Desktop, and we are running this experiment to understand how it impacts our users.\",\"lastSeen\":\"2023-09-11T17:58:25.169Z\",\"featureIds\":[\"fullPageTranslation\"],\"prefs\":[{\"name\":\"browser.translations.enable\",\"branch\":\"user\",\"featureId\":\"fullPageTranslation\",\"variable\":\"boolean\",\"originalValue\":null}],\"isRollout\":false}");
user_pref("nimbus.syncdatastore.fullPageTranslation.boolean", false);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"enrollmentId\":\"c5698b4a-3984-441e-84da-cb261da738ee\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2023-09-11T17:58:25.205Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2356a993-8e84-40e0-8e46-b0cb6f6ac7ed");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1694455103);
user_pref("toolkit.telemetry.cachedClientID", "f651faaf-930b-4693-842d-e16b1a66c72b");
user_pref("toolkit.telemetry.previousBuildID", "20230828231221");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
